site_name: Pathogen NGS 数据分析入门
site_description: '病原微生物高通量测序数据分析手册'
site_author: 'Mark Renton'
site_url: 'https://www.hzcdclab.org/site/'
theme: 'material'
copyright: 'Copyright &copy; 2016 - 2017 HZCDCLab'

extra:
  palette:
    primary: 'light blue'

pages:
  - '前言': index.md
  - '第一章 数据获取与质控':
    - '1.1 玩转 edirect': chapter_01/edirect.md
    - '1.2 基因组公共数据库': chapter_01/public_database.md
    - '1.3 模拟生成NGS数据': chapter_01/emulation.md
    - '1.4 提升Linux生产力': chapter_01/install.md
  - '第二章 基因组拼接和注释':
    - '2.1 基因组拼接': chapter_02/assembly.md
    - '2.1 spades': chapter_02/spades.md
    - '2.2 a5-miseq': chapter_02/a5-miseq.md
    - '2.3 masurca': chapter_02/masurca.md
    - '2.4 prokka': chapter_02/prokka.md
  - '第三章 基因组和序列比较':
    - '3.1 MUMmer': chapter_03/mummer.md
    - '3.2 C-Sibelia': chapter_03/c-sibelia.md
  - '第四章 多基因组分析':
    - '4.1 多重序列比对': chapter_04/msa.md
    - '4.2 Pan-Genomes 分析': chapter_04/pangenome.md
    - '4.3 Phylogenomics': chapter_04/phylogenomics.md
    #- '4.2 Roary 分析多基因组': chapter_04/roary.md
    #- '4.3 get_homologs': chapter_04/get_homologs.md
  - '第五章 基因组 SNP 分析应用':
    - '5.1 snp-pipeline': chapter_05/snp-pipeline.md
  - '第六章 数据分析可视化':
    - '6.1 igv': chapter_06/igv.md
    - '6.2 circos': chapter_06/circos.md
  - '第七章 宏基因组分析':
    - '7.1 16s 菌群分析': chapter_07/16s.md
    - '7.2 全基因组分析': chapter_07/shotgun.md
  - '第八章 基因组扫描工具':
    - '10.1 srst2 扫描 reads': chapter_08/srst2.md
    - '10.2 fasta 中获得 ST 数据': chapter_08/mlst.md
    - '10.3 ariba 扫描基因': chapter_08/ariba.md
  - '第九章 分析工具部署方式':
    - '9.1 基于 docker 镜像': chapter_09/docker.md
    - '9.2 Galaxy 平台': chapter_09/galaxy.md
    - '9.3 Amazon EC2 云平台': chapter_09/amazon.md
    - '9.4 其他平台': chapter_09/others.md
  - '第十章 基因组分析实践':
    - '10.1 SNP溯源应用一': chapter_10/case-01.md
    - '10.2 SNP溯源应用二': chapter_10/case-02.md
  - '附录':
    - 'A1. Linux 命令':
      - '1. Linux 系统基本命令': appendix/linux/basic.md
    - 'A2. Python 语言':
      - '1. biopython 基础': appendix/python/biopython.md
      - '2. Python 数据科学': appendix/python/data-science.md
    - 'A3. R 语言':
      - '1. ggplot2 入门': appendix/r/ggplot2.md
    - 'awk 和 bioawk': appendix/awk.md
    - '文件格式': appendix/fileformat.md
use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.superfences

google_analytics:
  - 'UA-55420348-2'
  - 'auto'
